# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=20
separator=false
markup=pango

[ethernet]
label=ETH:
command=ip addr show enp1s0 | grep -Po 'inet \K[\d.]+'
color=#b8bb26
interval=10

########################
separator_block_width=10
[spacer]
separator_block_width=10
full_text=
color=#8ec07c
########################


[disk]
label=HDD:
instance=/
command=df -h / | awk '/\// {print $3 " / " $2}'
color=#FFFFFF
interval=30

########################
separator_block_width=10
[spacer]
separator_block_width=10
full_text=
color=#8ec07c
########################

[memory]
label=RAM:
command=free -h | awk '/Mem.:/ {print $3 "/" $2}'
color=#FFEE00
interval=10

########################
separator_block_width=10
[spacer]
separator_block_width=10
full_text=
color=#8ec07c
########################

[cpu_usage]
command=$SCRIPT_DIR/cpu_usage/cpu_usage2 -l "CPU:"
interval=persist

########################
separator_block_width=10
[spacer]
separator_block_width=10
full_text=
color=#8ec07c
########################

[temperature]
command=$SCRIPT_DIR/temperature/temperature.sh
interval=5
color=#fb4934

########################
separator_block_width=10
[spacer]
separator_block_width=10
full_text=
color=#8ec07c
########################

[time]
label=
command=date +'%a %b %d %H:%M %Y'
color=#B8BB26
interval=5

########################
separator_block_width=10
[spacer]
separator_block_width=10
full_text=
color=#8ec07c
########################

[volume]
command=LABEL='VOL: ' $SCRIPT_DIR/volume/volume
interval=once
signal=10
#STEP=5%
#MIXER=[determined automatically]
#SCONTROL=[determined automatically]

