#!/bin/bash

CPU_USED=$(cat /proc/stat | grep '^cpu ' | awk '{sum=$2+$3+$4+$7+$8+$9+$10+$11}')
CPU_IDLE=$(cat /proc/stat | grep '^cpu ' | awk '{print $5}')
CPU_IOWAIT=$(cat /proc/stat | grep '^cpu ' | awk '{print $6}')
CPU_USAGE=$CPU_USED+$CPU_IDLE+$CPU_IOWAIT


